### PR TITLE
[minor] enforce comma dangle

### PR DESCRIPTION
**Pull request by leonardoanalista**
This will enforce in repos using global eslint config, for example `ahm-constants`. This rules is part of airbnb base but ahm-constants doesn't inherit this rule.

### CODE REVIEW

**Comment by camjc** [comment]
Probably this is old, but node hated dangling commas at one point?

**Comment by leonardoanalista** [comment]
ah good point

**Comment by cbovis** [comment]
What was the motivation behind this one? I believe we already enforce across the board via Prettier? https://prettier.io/docs/en/options.html#trailing-commas

**Comment by leonardoanalista** [comment]
I'll leave this on hold until I can test it out in the API

**Comment by cbovis** [comment]
As mentioned in Prettier docs @camjc, Node 8+ is fine with the danglers.

**Comment by leonardoanalista** [comment]
motivation is because constants is not enforcing this rule

**Comment by camjc** [comment]
This line should enforce https://github.com/ahmdigital/eslint-config/blob/master/global-config.js#L64

If it doesn't work we should fix there I think @leonardoanalista ?

**Pull request merged**
